### ISSUE TITLE
`Pool#connect` resolves error as success.

### ISSUE THREAD

**Issue by calebmer** [brianc/node-postgres#1142]
I initialized a pool using `pg.Pool` and then in an async function ran:

``` js
const client = await pgPool.connect()
client.query('begin')
...
client.query('commit')
client.release()
```

But I keep getting the error:

```
TypeError: client.query is not a function
```

Upon further investigation if I write:

``` js
const client = await pgPool.connect()
console.log(client)
```

I get the following:

```
{ Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432,
  release: [Function: bound ] }
```

Note the `release` property which gets added by the pool when it thinks it has a client.

**Comment by joskuijpers** [comment]
I am trying to figure out the origin.
The error should be occurring here: https://github.com/brianc/node-pg-pool/blob/master/index.js#L43
According to the code, it should bubble up to a promise rejection here: https://github.com/brianc/node-pg-pool/blob/master/index.js#L64

Not sure why this does not work.

Could you write a failing testcase for this?

**Comment by charmander** [comment]
Probably fixed by brianc/node-pg-pool#31 (note the double-callback bit at the end), though I only just noticed this bug so haven’t tested it.

**Comment by charmander** [comment]
Oh, nevermind; the double-callback was only for `query`, not `connect`.

I can’t reproduce this, though. Does something close to the following report failure correctly for you under the same circumstances?

```javascript
const pg = require('pg')

const pool = new pg.Pool()

pool.connect()
  .then(
    client => {
      console.log('success')
      client.release()
    },
    () => {
      console.log('failure')
    }
  )
  .then(
    () => { pool.end() }
  )
```

**Comment by loxy** [comment]
This is still an issue, right? Because I'm running exactly in this behavior.

**Comment by charmander** [comment]
@loxy

> Does something close to the following report failure correctly for you under the same circumstances?

**Comment by loxy** [comment]
Sorry, my fault. It works as expected. Had some strange side effects with another bug...
Thank you!
