### ISSUE TITLE
Hello I encountered connection terminated

### ISSUE THREAD

**Issue by baninaveen** [brianc/node-postgres#1427]
this is my config file 
`PG_CONFIG: {
	user: 'xxxxxx',
	database: 'xxxxxxxx',
	password: 'xxxxxxx',
	host: 'xxxxxxxxxxxx',
	port: 5432,
	max: 10,
	idleTimeoutMillis: 30000,
    },`

Also my app hosted on heroku this is my app coe

`'use strict';
const request = require('request');
const config = require('./config');
const pg = require('pg');
pg.defaults.ssl = true;

module.exports = {

    storeUserData: function(dataOne, dataTwo, userId) {
        var pool = new pg.Pool(config.PG_CONFIG);
        pool.connect(function(err, client, done) {
            if (err) {
                return console.error('Error acquiring client', err.stack);
            }
            let sql1 = `SELECT id FROM user_izo_data `;
            client
                .query(sql1,
                    function(err, result) {
                        if (err) {
                            console.log('Query error: ' + err);
                        } else {
                            console.log('rows: ' + result.rows.length);
                            if (result.rows.length === 0) {
                                let sql = 'INSERT INTO public.user_izo_data (psy_no, dest_no, fb_id) VALUES ($1, $2, $3)';
                            
                                client.query(sql,
                                [
                                    dataOne,
                                    dataTwo,
                                    userId
                                ]);
                            }
                        }
                    });

            done();
        });
        pool.end();
    }}`

**Comment by abenhamdine** [comment]
Could you please add the version of node-postgres you use & the exact error message ? Thx.

**Comment by baninaveen** [comment]
Thanks for quick reply 
` },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apiai": "^2.0.5",
    "body-parser": "^1.15.1",
    "express": "^4.13.4",
    "pg": "7.1.2",
    "request": "^2.72.0",
    "uuid": "^2.0.3"
  }
}
`

Error show Query error: Error: Connection terminated

**Comment by charmander** [comment]
`done()` returns the client to the pool. You need to call it after all queries have completed, not immediately after you send the first query.

```diff
 pool.connect(function(err, client, done) {
     if (err) {
         return console.error('Error acquiring client', err.stack);
     }
     let sql1 = `SELECT id FROM user_izo_data `;
     client
         .query(sql1,
             function(err, result) {
                 if (err) {
                     console.log('Query error: ' + err);
+                    done(err);
                 } else {
                     console.log('rows: ' + result.rows.length);
                     if (result.rows.length === 0) {
                         let sql = 'INSERT INTO public.user_izo_data (psy_no, dest_no, fb_id) VALUES ($1, $2, $3)';
 
                         client.query(sql,
                         [
                             dataOne,
                             dataTwo,
                             userId
-                        ]);
+                        ], done);
                     }
                 }
             });
-
-    done();
 });
```

You should also avoid creating a new pool each time and make use of `Pool#query` when possible:

```js
'use strict';

const request = require('request');
const config = require('./config');
const pg = require('pg');
pg.defaults.ssl = true;

const pool = new pg.Pool(config.PG_CONFIG);

module.exports = {
    storeUserData: function (dataOne, dataTwo, userId) {
        pool.query(`
            INSERT INTO public.user_izo_data (psy_no, dest_no, fb_id)
                SELECT $1, $2, $3 WHERE NOT EXISTS (SELECT id FROM user_izo_data)
        `, [dataOne, dataTwo, userId])
            .catch(console.error);
    },
};
```

**Comment by baninaveen** [comment]
I tries both the above code but I still get same error. In pgadmin it didn't show anything
